kube_apiserver_image: registry.fedoraproject.org/f27/kubernetes-apiserver
kube_controller_manager_image: registry.fedoraproject.org/f27/kubernetes-controller-manager
kube_scheduler_image: registry.fedoraproject.org/f27/kubernetes-scheduler
kube_kubelet_image: registry.fedoraproject.org/f27/kubernetes-kubelet
kube_proxy_image: registry.fedoraproject.org/f27/kubernetes-proxy