- name: install via system container
  atomic_container:
    name: flanneld
    image: "{{flanneld_image}}"
    backend: ostree
    state: latest
    mode: system
  when: not rpm_ostree_flanneld | default(false)
