- name: check version
  shell: flanneld --version
  register: flanneld_current_version
  failed_when: false
  check_mode: false
  changed_when: flanneld_version not in flanneld_current_version.stderr

- name: uninstall
  file:
    path: /usr/local/bin/flanneld
    state: absent
  when: flanneld_current_version.changed

- name: "install ({{flanneld_arch | default(ansible_architecture)}})"
  get_url:
    url: "https://github.com/coreos/flannel/releases/download/v{{flanneld_version}}/flanneld-{{flanneld_arch}}"
    dest: /usr/local/bin/flanneld
    remote_src: true
    mode: +x
  notify: 
    - restart flanneld on masters
    - restart flanneld and docker on minions

- block:
  - name: create required directories
    file:
      path: "{{item}}"
      state: directory
    loop:
      - /usr/libexec/flannel
      - /etc/systemd/system/docker.service.d

  - name: patch docker service
    copy:
      src: docker-dropin.conf
      dest: /etc/systemd/system/docker.service.d/40-flanneld-network.conf
    notify: 
      - restart flanneld on masters
      - restart flanneld and docker on minions

  - name: install docker opts script
    copy:
      src: mk-docker-opts.sh
      dest: /usr/libexec/flannel/mk-docker-opts.sh
      mode: +x
    notify: 
      - restart flanneld on masters
      - restart flanneld and docker on minions

  when: "'kube_minions' in group_names"

- name: create service
  template:
    src: service.j2
    dest: /etc/systemd/system/flanneld.service
  notify: 
    - restart flanneld on masters
    - restart flanneld and docker on minions

# wireguard tx checksum offload fix - https://github.com/xetys/hetzner-kube/issues/139#issuecomment-415570771
- block:
  - name: wireguard tx checksum offload fix - install ethtool
    apt:
      name: ethtool

  - name: wireguard tx checksum offload fix - create udev rule
    copy:
      src: flanneld.rules
      dest: /etc/udev/rules.d/71-flanneld.rules
    notify: restart systemd-udevd

  - name: wireguard tx checksum offload fix - create service
    copy:
      src: flanneld-wireguard@.service
      dest: /etc/systemd/system/flanneld-wireguard@.service

  when: flanneld_over_wireguard
