# install
# atomic packages are installed by basic role

- name: install (Debian)
  include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: create config directory
  file:
    path: "{{flanneld_config_dir}}"
    state: directory

# firewall
- name: setup firewall
  include_tasks: firewall.yml
  when: flanneld_configure_firewall

# pki
- name: copy pki
  include_role:
    name: pki
  vars:
    pki_dest_dir: "{{flanneld_pki_dir}}"

# cluster network config
- name: configure cluster network
  include_tasks: network_config.yml
  when: inventory_hostname == hostvars[groups['etcd_servers'][0]].inventory_hostname

# daemon config
- name: copy config (Atomic)
  template:
    src: flanneld.j2
    dest: "/etc/sysconfig/flanneld"
  notify: 
    - restart flanneld on masters
    - restart flanneld and docker on minions
  when: ansible_pkg_mgr == 'atomic_container'

- name: copy config (Debian)
  template:
    src: flanneld.j2
    dest: "/etc/default/flanneld"
  notify: 
    - restart flanneld on masters
    - restart flanneld and docker on minions
  when: ansible_os_family == 'Debian'

- name: enable flanneld
  systemd:
    name: flanneld
    enabled: true

- meta: flush_handlers
