# install
# atomic packages are installed by basic role

- name: install (Debian)
  include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

- name: create config directory
  file:
    path: "{{flanneld_config_dir}}"
    state: directory

# firewall
- name: setup firewall
  include_tasks: firewall.yml
  when: flanneld_configure_firewall

# pki
- name: copy pki
  include_role:
    name: pki
  vars:
    pki_dest_dir: "{{flanneld_pki_dir}}"

# network config
- block:
  - name: copy cluster config
    template:
      src: flanneld-config.json.j2
      dest: "{{flanneld_config_dir}}/flanneld-config.json"
    register: flanneld_config

  - name: upload cluster config to etcd
    shell: |
      etcdctl --endpoints https://{{inventory_hostname}}.{{kube_domain}}:{{etcd_port}} \
      --ca-file {{etcd_pki_dir}}//certs/ca.crt \
      --cert-file {{etcd_pki_dir}}/certs/{{inventory_hostname}}.crt \
      --key-file {{etcd_pki_dir}}/keys/{{inventory_hostname}}.key \
      set {{flanneld_network_name}}/network/config < {{flanneld_config_dir}}/flanneld-config.json
    when: flanneld_config.changed
    ignore_errors: true
    register: flanneld_config_upload

  - name: reset config
    file:
      path: "{{flanneld_config_dir}}/flanneld-config.json"
      state: absent
    failed_when: true
    when: flanneld_config_upload is failed

  when: inventory_hostname == hostvars[groups['etcd_servers'][0]].inventory_hostname

# daemon config
- name: copy config (Atomic)
  template:
    src: flanneld.j2
    dest: "/etc/sysconfig/flanneld"
  notify: 
    - restart flanneld on masters
    - restart flanneld and docker on minions
  when: ansible_pkg_mgr == 'atomic_container'

- name: copy config (Debian)
  template:
    src: flanneld.j2
    dest: "/etc/default/flanneld"
  notify: 
    - restart flanneld on masters
    - restart flanneld and docker on minions
  when: ansible_os_family == 'Debian'

- name: enable flanneld
  systemd:
    name: flanneld
    enabled: true

- meta: flush_handlers
