- name: copy cluster network config
  template:
    src: flanneld-config.json.j2
    dest: "{{flanneld_config_dir}}/flanneld-config.json"
  register: flanneld_config

- name: check for cluster network config in etcd
  shell: |
    etcdctl --endpoints https://{{inventory_hostname}}.{{kube_domain}}:{{etcd_port}} \
    --ca-file {{etcd_pki_dir}}//certs/ca.crt \
    --cert-file {{etcd_pki_dir}}/certs/{{inventory_hostname}}.crt \
    --key-file {{etcd_pki_dir}}/keys/{{inventory_hostname}}.key \
    get {{flanneld_network_name}}/network/config
  changed_when: "'Key not found' in flanneld_config_etcd.stderr"
  failed_when: false
  register: flanneld_config_etcd

- name: upload cluster network config to etcd
  shell: |
    etcdctl --endpoints https://{{inventory_hostname}}.{{kube_domain}}:{{etcd_port}} \
    --ca-file {{etcd_pki_dir}}//certs/ca.crt \
    --cert-file {{etcd_pki_dir}}/certs/{{inventory_hostname}}.crt \
    --key-file {{etcd_pki_dir}}/keys/{{inventory_hostname}}.key \
    set {{flanneld_network_name}}/network/config < {{flanneld_config_dir}}/flanneld-config.json
  when: flanneld_config.changed or flanneld_config_etcd.changed
