- name: create directory structure
  file:
    name: "{{item}}"
    state: directory
  loop: 
    - "{{pki_dir}}"
    - "{{pki_dir}}/certs"
    - "{{pki_dir}}/keys"
    - "{{pki_dir}}/configs"
    - "{{pki_dir}}/requests"

- name: protect pki keys
  file:
    name: "{{pki_dir}}/keys"
    mode: 0700

- name: create ca key
  shell: "openssl genrsa -out {{pki_dir}}/keys/ca.key 4096"
  args:
    creates: "{{pki_dir}}/keys/ca.key"

- name: create ca certificate
  shell: |
    openssl req -x509 -new -nodes -key {{pki_dir}}/keys/ca.key \
    -subj "/CN={{kube_cluster_name}}-kubernetes" -days 3650 \
    -out {{pki_dir}}/certs/ca.crt
  args:
    creates: "{{pki_dir}}/certs/ca.crt"

- name: create certificates
  include_tasks: cert.yml
  loop: "{{groups.pki_certs}}"
