- name: init
  include_tasks: init.yml
  when: (pki_dest_dir is none) and 
        (inventory_hostname == hostvars[pki_master].inventory_hostname)

- name: copy to destination
  include_tasks: copy.yml
  when: pki_dest_dir is not none
