- name: copy config
  template:
    src: docker-storage-setup.j2
    dest: /etc/sysconfig/docker-storage-setup
  register: storageconfig
  
- block:
  - file:
      path: /etc/sysconfig/docker-storage
      state: absent

  - name: "create empty filesystem"
    filesystem:
      fstype: xfs
      dev: "{{storage_drive}}"
      opts: -f

  - name: grow docker storage
    shell: docker-storage-setup
    ignore_errors: true
    register: dockersetup

  - name: grow root fs
    shell: xfs_growfs /
    when: dockersetup is succeeded

  - name: remove config
    file:
      path: /etc/sysconfig/docker-storage-setup
      state: absent
    when: dockersetup is failed

  - debug:
      msg: "FATAL: docker storage setup was not successfull, reboot and try again"
    failed_when: true
    when: dockersetup is failed
  
  when: storageconfig.changed