- name: storage-setup (Atomic)
  include_tasks: atomic.yml
  when:  ansible_pkg_mgr == 'atomic_container'

- name: storage-setup (Raspbian)
  include_tasks: raspbian.yml
  when: "ansible_lsb.id is defined and
        ansible_lsb.id == 'Raspbian'"
