- name: install kubectl (RedHat)
  dnf:
    name: kubernetes-client
  become: true
  when: ansible_os_family == 'RedHat'

- name: fetch certificates
  include_role: 
    name: pki
  vars:
    pki_dest_dir: "{{kubectl_cert_folder}}"
    pki_dest_dir_owner: "{{ansible_user_id}}"
    pki_dest_dir_group: "{{ansible_user_gid}}"
    inventory_hostname: client

- name: set kubectl context
  shell: |
    kubectl config set-cluster {{kube_cluster_name}}-cluster \
    --server=https://{{kubectl_apiserver_domain}}:{{kube_apiserver_port}} \
    --certificate-authority={{kubectl_cert_folder}}/certs/ca.crt

    kubectl config set-credentials {{kube_cluster_name}}-admin \
    --client-certificate={{kubectl_cert_folder}}/certs/client.crt \
    --client-key={{kubectl_cert_folder}}/keys/client.key

    kubectl config set-context {{kube_cluster_name}} \
    --cluster={{kube_cluster_name}}-cluster \
    --user={{kube_cluster_name}}-admin --namespace=default
  args:
    executable: /bin/bash
