- name: install etcd via rpm-ostree
  include_role: 
    name: rpm-ostree
  vars:
    rpm_ostree_package: etcd
    rpm_ostree_version: "{{etcd_version}}"
    rpm_ostree_binary_path: /usr/bin/etcd
  when: "'kube_masters' in group_names"

- meta: flush_handlers
