- name: check version (Debian)
  shell: etcd --version
  register: etcd_version
  ignore_errors: true
  changed_when: false
  check_mode: false
  when: "etcd_arch is not defined or
        etcd_arch is defined and
        etcd_arch != 'arm'"

- name: check version (arm)
  shell: ETCD_UNSUPPORTED_ARCH=arm etcd --version
  register: etcd_version
  ignore_errors: true
  changed_when: false
  check_mode: false
  when: "etcd_arch is defined and
        etcd_arch == 'arm'"

# supported Debian
- block:
  - name: "install ({{ansible_architecture}})"
    unarchive:
      src: "https://github.com/coreos/etcd/releases/download/{{etcd_download_version}}/etcd-{{etcd_download_version}}-linux-{{etcd_arch | default(ansible_architecture)}}.tar.gz"
      dest: "{{etcd_download_dir}}"
      remote_src: true

  - copy:
      src: "{{etcd_download_dir}}/etcd-{{etcd_download_version}}-linux-{{etcd_arch | default(ansible_architecture)}}/{{item}}"
      dest: "/usr/local/bin/{{item}}"
      remote_src: true
      mode: +x
    with_items:
      - etcd
      - etcdctl
    notify: restart etcd
  
  - file:
      path: "{{etcd_download_dir}}/etcd-{{etcd_download_version}}-linux-{{etcd_arch | default(ansible_architecture)}}"
      state: absent

  when: "not etcd_install_local_binary and
        etcd_download_version not in etcd_version.stdout"

# install from local binary
- block:
  - shell: echo $GOPATH
    register: gopath
    changed_when: false
    delegate_to: localhost
    become: false

  - name: install from local binary
    copy:
      src: "{{gopath.stdout}}/src/github.com/coreos/etcd/bin/{{item}}"
      dest: "/usr/local/bin/{{item}}"
      mode: +x
    with_items:
      - etcd
      - etcdctl
    notify: restart etcd
  
  when: etcd_install_local_binary and
        etcd_version|failed

- name: create etcd user
  user:
    name: etcd

- name: chown etcd lib
  file:
    path: /var/lib/etcd
    owner: etcd
    group: etcd

- name: create service
  template:
    src: service.j2
    dest: /etc/systemd/system/etcd.service
  notify: restart etcd