- block:
  # install
  - name: install (Atomic)
    include_tasks: install_atomic.yml
    when: is_atomic | default(false)

  - name: install (Debian)
    include_tasks: install_debian.yml
    when: ansible_os_family == 'Debian'

  # pki
  - include_role:
      name: pki
    vars:
      cert_folder: "{{etcd_cert_folder}}"

  # config
  - name: copy config
    template:
      src: etcd.j2
      dest: "{{etcd_config_folder}}/etcd.conf"
    notify: restart etcd

  - name: enable etcd
    systemd:
      name: etcd
      enabled: true

  - meta: flush_handlers

  when: "'etcd_servers' in group_names"