- block:
  # install
  # atomic packages are installed by basic role

  - name: install (Debian)
    include_tasks: install_debian.yml
    when: ansible_os_family == 'Debian'

  # pki
  - name: copy pki
    include_role:
      name: pki
    vars:
      pki_dest_dir: "{{etcd_pki_dir}}"
      pki_dest_dir_owner: etcd
      pki_dest_dir_group: etcd

  # configure
  - name: create config directory
    file:
      path: /etc/etcd
      state: directory

  - name: copy config
    template:
      src: etcd.j2
      dest: "{{etcd_config_dir}}/etcd.conf"
    notify: restart etcd

  - name: enable etcd
    systemd:
      name: etcd
      enabled: true


  when: "'etcd_servers' in group_names"

- meta: flush_handlers
