- block:
  # install
  # atomic packages are installed by basic role

  - name: install (Debian)
    include_tasks: install_debian.yml
    when: ansible_os_family == 'Debian'

  # pki
  - name: copy pki
    include_role:
      name: pki
    vars:
      pki_dest_dir: "{{etcd_pki_dir}}"
      pki_dest_dir_owner: etcd
      pki_dest_dir_group: etcd

  # configure
  - name: create config directory
    file:
      path: /etc/etcd
      state: directory

  - name: copy config
    template:
      src: etcd.j2
      dest: "{{etcd_config_dir}}/etcd.conf"
    notify: restart etcd

  - name: enable etcd
    systemd:
      name: etcd
      enabled: true

  - name: restore snapshot
    shell: |
      sudo -u etcd bash -c 'ETCDCTL_API=3 etcdctl \
        snapshot restore {{etcd_snapshot_dir}}/{{etcd_restore_snapshot}} \
        --data-dir="/var/lib/etcd/{{inventory_hostname}}.etcd"'
    args:
      warn: false
    when: etcd_restore_snapshot is not none

  when: "'etcd_servers' in group_names"

- meta: flush_handlers

# snapshots
- include_tasks: snapshots.yml
  when: "'etcd_servers' in group_names
        and etcd_enable_snapshots"
