- name: "download system image"
  get_url:
    url: "{{virt_image_url}}"
    dest: "{{virt_drives_dir}}/{{virt_image}}"
    mode: 0644
    owner: libvirt-qemu
    group: libvirt-qemu

- name: install python-libvirt
  apt:
    name: python-libvirt

- name: create virtual machine
  include_tasks: vm_creation.yml
  loop: "{{groups.virtual_machines}}"

- name: start virtual machine
  virt:
    name: "{{hostvars[item].vm_name}}"
    state: running
  loop: "{{groups.virtual_machines}}"
