- name: check for previous system image
  stat:
    path: "{{virt_drives_dir}}/{{hostvars[item].virt_vm_name}}.qcow2"
  register: system_image

- name: copy system image
  copy:
    remote_src: true
    src: "{{virt_drives_dir}}/{{virt_image}}"
    dest: "{{virt_drives_dir}}/{{hostvars[item].virt_vm_name}}.qcow2"
    owner: libvirt-qemu
    group: libvirt-qemu
    mode: 0600
  when: not system_image.stat.exists

- name: create lvm data partition
  lvol:
    vg: "{{virt_lvm_vg}}"
    lv: "{{hostvars[item].virt_vm_name}}-data"
    size: "{{hostvars[item].virt_data_size | default(virt_data_size)}}"

- name: create virtual machine
  virt:
    name: "{{hostvars[item].virt_vm_name}}"
    command: define
    xml: "{{lookup('template', 'k8s-vm.xml.j2')}}"
