- name: install etcd via rpm-ostree
  include_role: 
    name: rpm-ostree
  vars:
    rpm_ostree_package: etcd
    rpm_ostree_version: "{{etcd_version}}"
    rpm_ostree_binary_path: /usr/bin/etcd
  when: "'kube_masters' in group_names"

- name: install flanneld via rpm-ostree
  include_role: 
    name: rpm-ostree
  vars:
    rpm_ostree_package: flannel
    rpm_ostree_version: "{{flanneld_version}}"
    rpm_ostree_binary_path: /usr/bin/flanneld

- name: install kubernetes-master via rpm-ostree
  include_role: 
    name: rpm-ostree
  vars:
    rpm_ostree_package: kubernetes-master
    rpm_ostree_version: "{{kube_version}}"
    rpm_ostree_binary_path: /usr/bin/kube-apiserver
  when: "'kube_masters' in group_names"

- name: install kubernetes-node via rpm-ostree
  include_role: 
    name: rpm-ostree
  vars:
    rpm_ostree_package: kubernetes-node
    rpm_ostree_version: "{{kube_version}}"
    rpm_ostree_binary_path: /usr/bin/kubelet
  when: "'kube_minions' in group_names"

- meta: flush_handlers
