- name: install flannel via rpm-ostree
  shell: rpm-ostree install flannel
  args:
    creates: /usr/bin/flanneld
  notify: reboot
  when: rpm_ostree_flanneld | default(false)

- name: install etcd via rpm-ostree
  shell: rpm-ostree install etcd
  args:
    creates: /usr/bin/etcd
  notify: reboot
  when: "'kube_masters' in group_names and rpm_ostree_etcd | default(false)"

- name: install kubernetes-master via rpm-ostree
  shell: rpm-ostree install kubernetes-master
  args:
    creates: /usr/bin/kube-apiserver
  notify: reboot
  when: "'kube_masters' in group_names and rpm_ostree_kubernetes | default(false)"

- name: install kubernetes-node via rpm-ostree
  shell: rpm-ostree install kubernetes-node
  args:
    creates: /usr/bin/kubelet
  notify: reboot
  when: "'kube_minions' in group_names and rpm_ostree_kubernetes | default(false)"