- name: add localhost entries
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: disable selinux permanently
  lineinfile:
    path: /etc/selinux/config
    regexp: 'SELINUX='
    line: 'SELINUX=disabled'
  notify: disable selinux
  when: ansible_selinux_python_present
