- name: add localhost entries
  template:
    src: hosts.j2
    dest: /etc/hosts

- name: disable selinux permanently
  lineinfile:
    path: /etc/selinux/config
    regexp: 'SELINUX='
    line: 'SELINUX=disabled'
  notify: disable selinux
  when: ansible_selinux_python_present

- name: install atomic packages
  include_tasks: atomic_rpm_install.yml
  when: ansible_pkg_mgr == 'atomic_container'

- name: install requirements
  apt:
    name: ca-certificates
  when: ansible_pkg_mgr == 'apt'

- meta: flush_handlers
