# master only block
- block:
  - name: install kubernetes master components via atomic containers
    atomic_container:
      name: "{{item.name}}"
      image:  "{{item.image}}"
      backend: ostree
      state: latest
      mode: system
    with_items:
      - name: kube-apiserver
        image: "{{kube_apiserver_image}}"
      - name: kube-controller-manager
        image:  "{{kube_controller_manager_image}}"
      - name: kube-scheduler
        image: "{{kube_scheduler_image}}"

  # FIX: Unable to find suitable network address.error='No default routes.'.
  - name: patch kube-apiserver service (Atomic 27)
    file:
      path: /etc/systemd/system/kube-apiserver.service.d
      state: directory
    when: ansible_distribution_major_version == '27'
  - copy:
      src: kube-apiserver-dropin.conf
      dest: /etc/systemd/system/kube-apiserver.service.d/override.conf
    notify: systemd reload

  when: "'kube_masters' in group_names"

# minion only
- name: install kubernetes minion components via atomic containers
  atomic_container:
    name: kubelet
    image: "{{kube_kubelet_image}}"
    backend: ostree
    state: latest
    mode: system
  with_items:
    - name: kubelet
      image: "{{kube_kubelet_image}}"
    - name: kube-proxy
      image:  "{{kube_proxy_image}}"
  when: "'kube_minions' in group_names" 
