# master only block
- block:
  - name: install kube-apiserver
    atomic_container:
      name: kube-apiserver
      image:  "{{kube_apiserver_image}}"
      backend: ostree
      state: latest
      mode: system

  - name: install kube-controller-manager
    atomic_container:
      name: kube-controller-manager
      image:  "{{kube_controller_manager_image}}"
      backend: ostree
      state: latest
      mode: system

  - name: install kube-scheduler
    atomic_container:
      name: kube-scheduler
      image: "{{kube_scheduler_image}}"
      backend: ostree
      state: latest
      mode: system

  # FIX: Unable to find suitable network address.error='No default routes.'.
  - name: patch kube-apiserver service
    file:
      path: /etc/systemd/system/kube-apiserver.service.d
      state: directory
  - copy:
      src: kube-apiserver-dropin.conf
      dest: /etc/systemd/system/kube-apiserver.service.d/override.conf
    notify: systemd reload

  when: "'kube_masters' in group_names"

# minion only block
- block:
  - name: install kubelet
    atomic_container:
      name: kubelet
      image: "{{kube_kubelet_image}}"
      backend: ostree
      state: latest
      mode: system

  - name: install kube-proxy
    atomic_container:
      name: kube-proxy
      image: "{{kube_proxy_image}}"
      backend: ostree
      state: latest
      mode: system

  when: "'kube_minions' in group_names"

# FIX: exec kube-apiserver-docker.sh permission denied
# - name: FIX binaries
#   shell: "chmod a+x /sysroot/ostree/deploy/fedora-atomic/var/lib/containers/atomic/kube*/rootfs/usr/bin/kube*"
#   changed_when: false