- name: install kubernetes-master via rpm-ostree
  include_role: 
    name: rpm-ostree
  vars:
    rpm_ostree_package: kubernetes-master
    rpm_ostree_version: "{{kube_version}}"
    rpm_ostree_binary_path: /usr/bin/kube-apiserver
  when: "'kube_masters' in group_names"

- name: install kubernetes-node via rpm-ostree
  include_role: 
    name: rpm-ostree
  vars:
    rpm_ostree_package: kubernetes-node
    rpm_ostree_version: "{{kube_version}}"
    rpm_ostree_binary_path: /usr/bin/kubelet
  when: "'kube_minions' in group_names"
