# install
- include_tasks: install_atomic.yml
  when: is_atomic | default(false) and not rpm_ostree_kubernetes | default(false)

- include_tasks: install_debian.yml
  when: ansible_os_family == 'Debian'

# pki
- include_role:
    name: pki
  vars:
    cert_folder: "{{kube_cert_folder}}"

# main config
- name: copy main config
  template:
    src: config.j2
    dest: "{{kube_config_folder}}/config"
  notify: 
    - restart kubelet
    - restart kube-apiserver
- name: copy kube config
  template:
    src: kubeconfig.j2
    dest: "{{kube_config_folder}}/kubeconfig"
  notify: 
    - restart kubelet
    - restart kube-apiserver

# master only block
- block:
  # apiserver
  - name: copy apiserver config
    template:
      src: apiserver.j2
      dest: "{{kube_config_folder}}/apiserver"
    notify: restart kube-apiserver
  # controller-manager
  - name: copy controller-manager config
    template:
      src: controller-manager.j2
      dest: "{{kube_config_folder}}/controller-manager"
    notify: restart kube-controller-manager
  when: "'kube_masters' in group_names"

# minions only block
- block:
  # kubelet
  - name: copy kubelet config
    template:
      src: kubelet.j2
      dest: "{{kube_config_folder}}/kubelet"
    notify: restart kubelet
  # proxy
  - name: copy proxy config
    template:
      src: proxy.j2
      dest: "{{kube_config_folder}}/proxy"
    notify: restart kube-proxy
  when: "'kube_minions' in group_names"

- meta: flush_handlers
