# apiserver
- name: copy apiserver config
  template:
    src: apiserver.j2
    dest: "{{kube_config_folder}}/apiserver"
  notify: restart kube-apiserver

# controller-manager
- name: copy controller-manager config
  template:
    src: controller-manager.j2
    dest: "{{kube_config_folder}}/controller-manager"
  notify: restart kube-controller-manager

- name: enable kubernetes master components
  systemd:
    name: "{{item}}"
    enabled: true
  loop:
    - kube-apiserver
    - kube-scheduler
    - kube-controller-manager

# kubeconfig for insecure local access
- name: create kubectl config directory
  file:
    path: "/home/{{ansible_env.SUDO_USER}}/.kube"
    state: directory
    owner: "{{ansible_env.SUDO_USER}}"

- name: copy kubeconfig for insecure access
  template:
    src: kubeconfig_user.j2
    dest: "/home/{{ansible_env.SUDO_USER}}/.kube/config"
    owner: "{{ansible_env.SUDO_USER}}"
