# rbac bootstrap
- name: copy rbac bootstrap config
  template:
    src: bootstrap/rbac.yml.j2
    dest: "/home/{{ansible_env.SUDO_USER}}/rbac-bootstrap.yml"
    owner: "{{ansible_env.SUDO_USER}}"
  register: rbac_bootstrap_config

- name: apply rbac bootstrap config
  shell: kubectl apply -f rbac-bootstrap.yml
  become: false
  register: rbac_bootstrap
  changed_when: "'created' in rbac_bootstrap.stdout 
                or ' changed' in rbac_bootstrap.stdout"
