- name: install (Debian)
  include_tasks: install_debian.yml
  when: "ansible_os_family == 'Debian' and
        'kube_minions' in group_names"

- include_tasks: atomic-29-fix.yml
  when: "ansible_pkg_mgr == 'atomic_container'
        and ansible_distribution_major_version == '29'
        and 'kube_minions' in group_names"

- meta: flush_handlers
