flanneld_network_name: minion
# flanneld network with subnet mask
flanneld_network: 172.16.0.0/16
flanneld_interface: flannel.1
flanneld_configure_firewall: true
# optional: interface used for peer to peer connection, 
# e.g. wg0 for an existing wireguard vpn
flanneld_host_interface:
# ethtool fix for wireguard (debian only)
# important: set flanneld_host_interface to the wireguard interface
flanneld_over_wireguard: false 

flanneld_config_dir: /etc/flanneld
flanneld_pki_dir: /etc/flanneld/pki
flanneld_version: 0.10.0
flanneld_arch: amd64

# etcd
etcd_pki_dir: "{{flanneld_pki_dir}}"
etcd_port: 2379
