flanneld_network_name: minion
# flanneld network with subnet mask
flanneld_network: 172.16.0.0/16
flanneld_configure_firewall: false

flanneld_config_dir: /etc/flanneld
flanneld_pki_dir: /etc/flanneld/pki
flanneld_version: 0.10.0
flanneld_arch: amd64

# etcd
etcd_pki_dir: "{{flanneld_pki_dir}}"
etcd_port: 2379
